project:
  type: website
theme:
  light: [h1hack.scss, brand]
highlight-style: a11y
website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - renderings.qmd
profile:
  group: 
    - 
      - none
      - color
      - typography1
      - typography2
      - typography3
      - logo
      - ecological-balance
      - tidal-equity
      - quantum-linguistics
      - orions-reach
